# image: node:latest

# services:
# - docker:dind

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/

build:
  stage: build
  image:
    - node:latest
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
     - server/
     - public/
     # - node_modules/

test:
  stage: test
  variables:
    DATABASE_URL: "mongodb://mongo/FeathersVueTest"
    NODE_ENV: "test"
  image: node:latest
  services:
    - mongo
  script:
    - npm run mocha

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
    - docker version
    - docker-compose version
  script:
    - docker-compose stop
    - docker-compose build web --no-cache
    - docker-compose up -d

variables:
  # STAGING_REGISTRY: "my-docker-hub"
  # CONTAINER_TEST_IMAGE: ${STAGING_REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}_test
  # CONTAINER_RELEASE_IMAGE: ${STAGING_REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}