cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/

build:
  stage: build
  image: node:latest
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
     - server/
     - public/

test:
  stage: test
  image: node:latest
  variables:
    DATABASE_URL: "mongodb://mongo/FeathersVueTest"
    NODE_ENV: "test"
  services:
    - mongo
  script:
    - npm run mocha

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    # The Gitlab Registry
    GL: "registry.gitlab.com"
    # Docker Hub Image Name
    IMG: "$CI_PROJECT_PATH"
    # Experimental: test the overlayfs docker driver.
    DOCKER_DRIVER: "overlay"

  before_script:
    - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
    - docker version
    - docker-compose version
    - "docker info"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $GL"
  script:
    - printf "DATABASE_URL=${DATABASE_URL}\nPORT=${PORT}\n" > environment.env
    - docker-compose stop
    - docker-compose build web --no-cache
    - "docker push $GL/$IMG:latest"
  after_script:
    - "docker images"
    - "docker logout $GL"


variables:
  # STAGING_REGISTRY: "my-docker-hub"
  # CONTAINER_TEST_IMAGE: ${STAGING_REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}_test
  # CONTAINER_RELEASE_IMAGE: ${STAGING_REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}