db:
  image: mongo
  expose:
    - "27017"
    - "37017"
  command: --smallfiles
web:
  image: registry.gitlab.com/codingfriend/feathers-vue:latest
  ports:
    - "80:80"
  env_file:
    - environment.env
  links:
    - db:db
