version: '3'
services:
  db:
    image: mongo:3.2.16
    expose:
      - "27017"
      - "37017"
    command: --smallfiles
    logging:
      driver: none
  web:
    build: .
    env_file:
      - environment-dev.env
    ports:
      - "3030:3030"
    volumes:
      - .:/var/www/:delegated
      - /var/www/node_modules
    links:
      - db:db
